### PR TITLE
Added function to change tab title/icon color when selected.

### PR DESCRIPTION
**Pull request by red1004g**
Currently, only the interactive indicator can be modified in the tabs just like on the Google Play Store.
This modification allows selected tab title/icons to be of different color, making the interface more flexible and intuitive.
I added some functions in the library, and applied them on the sample.
# library
- pstsTabSwith(boolean) :  When a tab is selected, the drawable selector icon or the text color of the Tab title can be modified
- pstsActivateTextColor(int) : The Title color of selected Tab
- pstsDeactivateTextColor(int) : The Title color of unselected Tabs

I believe these additions will diversify the usage of this project, paving the way for a better interface.

Thank you for sharing a great open source.

Comments and suggestions are welcome!

### CODE REVIEW

**Comment by camposbrunocampos** [comment]
Hello Guys, turns out that there is a better solution. 
You could just create a selector resource inside `res/colors/` and use it in your PagerSlidingStrip android:textColor attribute. I`ll print the code below. 
The text will change its color like a selector button, simple like that. There is no need of changing the lib.

<h3>res/color/btn</h3>
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true"
        android:color="#000000" /> 
    <item android:state_focused="true"
        android:color="@color/active_text" /> 
    <item android:color="#FFFFFF" /> 
</selector>


and here is where I use this resource in `andorid:textColor attribute`
<h3>slideFragment.xml</h3>
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <com.astuetz.PagerSlidingTabStrip
        android:id="@+id/pager_title"
        android:layout_width="match_parent"
        style="@style/PagerTitleStrip"
        android:layout_gravity="top"
        android:textColor="@color/btn"
        android:textSize="13sp"
        android:paddingBottom="@dimen/padding_logo"
        android:paddingTop="@dimen/padding_logo"
        app:pstsIndicatorColor="@color/border_title_strip"
        android:layout_height="@dimen/height_pager_title_strip"/>
    <android.support.v4.view.ViewPager
        android:id="@+id/pager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="1">

    </android.support.v4.view.ViewPager>
</LinearLayout>
```

**Comment by PrathmK** [comment]
can i set the custom icon width
if i want to set the 80% of the total width to the tab that is currently selected.

**Comment by alejouribesanchez** [comment]
Good work!!, thanks a lot!!!

**Comment by adicsarch** [comment]
Saved a lot of time!! Thanks a lot!!!

**Comment by iamaunz** [comment]
I got "No resource identifier found for attribute 'pstsTabSwitch'" when use app:pstsTabSwitch="true" any suggestion ?

**Comment by alxhotel** [comment]
This works great !! Thanks

**Comment by vietmh** [comment]
I got the same problem with @iamaunz ("No resource identifier found for attribute 'pstsTabSwitch'"). 
What should I do ? 
Should I download the code directly from github and push it into gradle file ? 
I'm currently put this "compile 'com.astuetz:pagerslidingtabstrip:1.0.1'" into gradle file.

**Comment by rml-anh-nguyen** [comment]
@camposbrunocampos did anyone confirm this ? because it's not work in mine project

**Comment by phitsanukae** [comment]
Lava600
เมื่อ 9 พ.ค. 2016 11:00 ก่อนเที่ยง "rml-anh-nguyen" <
notifications@github.com> เขียนว่า

**Comment by UnateD** [comment]
@rml-anh-nguyen @devabir93 @vietmh @iamaunz @EugeneHoran @abhijith-gururaj 
Pay attention to this link. Perhaps it is the same library, simply filled in another repository
https://github.com/jpardogo/PagerSlidingTabStrip

To change the color of the text is necessary to make drawable like
`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/black" android:state_selected="true" />
    <item android:color="#ff0000" android:state_selected="false" />
</selector>`

and then apply to the property 

`app:pstsTabTextColor="@drawable/test"`

Now the text color changes when the tab is active. In the description of the link has a lot of new properties

**Pull request closed without merging**
